mocks/helpers.js
mocks/mockWS.js
mocks/ranger.js

Feature: Mockserver reloads on file changes

Feature: Add incremental orderbook support in mockserver

---

src/components/CombinedOrderBook/CombinedOrderBook.pcss
src/components/CombinedOrderBook/CombinedOrderBook.test.tsx
src/components/CombinedOrderBook/__snapshots__/CombinedOrderBook.test.tsx.snap
src/components/CombinedOrderBook/index.tsx
src/components/CombinedOrderBook/readme.md
src/components/OrderBook/OrderBook.pcss
src/components/OrderBook/OrderBook.test.tsx
src/components/OrderBook/__snapshots__/OrderBook.test.tsx.snap
src/components/OrderBook/index.tsx
src/components/OrderBook/readme.md
src/components/index.ts
src/containers/Confirm/Documents/index.tsx
src/containers/HistoryElement/index.tsx
src/containers/Markets/index.tsx
src/containers/OpenOrders/OpenOrders.pcss
src/containers/OpenOrders/index.tsx
src/containers/Order/Order.pcss
src/containers/Order/index.tsx
src/containers/OrderBook/OrderBook.pcss
src/containers/OrderBook/index.tsx
src/containers/OrdersElement/index.tsx
src/containers/RecentTrades/RecentTrades.pcss
src/containers/RecentTrades/Yours.tsx
src/routes/Layout/index.tsx
src/screens/ConfirmScreen/ConfirmScreen.pcss
src/screens/EmailVerification/index.tsx
src/screens/History/HistoryTab.pcss
src/screens/OrdersTabScreen/OrdersTabScreen.pcss
src/screens/WalletsScreen/WalletsScreen.pcss
src/screens/WalletsScreen/index.tsx

Feature: move CombinedOrderBook, replace Loader with bootstrap element

---

src/containers/OrderBook/OrderBook.pcss
src/helpers/layout.ts
src/screens/TradingScreen/index.tsx

https://jira.openware.work/browse/WEB-25

Feature: modify Trading Screen layout

---

src/containers/Alerts/Alerts.pcss

https://jira.openware.work/browse/CHAIN-14

Fix: change alert layer

---

src/containers/HeaderToolbar/index.tsx
src/containers/ToolBar/MarketSelector/MarketsList/index.tsx

https://jira.openware.work/browse/BF-162

Fix: change volume precision to display

---

src/modules/user/ordersHistory/sagas/ordersHistoryCancelSaga.ts

Fix: make OpenOrdersCancelSaga api configurable depending on using finex or peatio

---

src/containers/HistoryElement/index.tsx
src/helpers/helpers.test.ts
src/helpers/index.ts
src/helpers/truncateMiddle.ts

Fix: add address middle truncation

---

src/screens/EmailVerification/index.tsx
src/screens/SignInScreen/index.tsx

Fix: fetch email from user interface at email verification screen

---

src/mobile/components/ModalWithdrawConfirmation/index.tsx
src/mobile/components/WalletWithdrawBody/index.tsx
src/mobile/components/index.ts
src/mobile/styles/components/Modal.pcss
src/mobile/styles/components/ModalWithdrawConfirmation.pcss
src/mobile/styles/components/WalletWithdrawBody.pcss
src/mobile/styles/components/styles.pcss
src/mobile/translations/en.ts
yarn.lock

https://jira.openware.work/browse/CORE-369

Feature: Withdraw Confirmation mobile modal

---

src/api/config.ts
src/api/index.ts
src/api/types.ts
src/constants/constants.test.ts
src/constants/index.ts
src/helpers/jest.ts
src/modules/public/ranger/sagas/rangerSaga.test.ts

- prevent crashes on missing variables
- put default variables on missing from the config

Feature: refactor process environment variables

---

src/modules/user/apiKeys/reducer.test.ts
src/modules/user/apiKeys/reducer.ts

proper redux state fixes the bug.
https://jira.openware.work/browse/EMI-320

Fix: handle API Key error in reducer

---

src/containers/ToolBar/MarketSelector/MarketSelector.pcss
src/containers/ToolBar/ToolBar.pcss

https://jira.openware.work/browse/EMI-354

Fix: trade page market selector search field overflow

---

package.json
yarn.lock

bump axios once more after "webpack" pr merge

Fix: bump axios to 0.21.1

---

src/components/Beneficiaries/index.tsx
src/containers/ReferralProgram/ReferralProgram.pcss
src/containers/TradingChart/TradingChart.pcss
src/screens/WalletsScreen/index.tsx

1. Remove duplicating code from Beneficiary component.
2. Trigger beneficiary fetch after successful creation
3. Stay on selected tab if switch wallet
4. Trading chart height
5. Fix referral link field width

Fix: wallets and trading view issues

---

src/components/Beneficiaries/Beneficiaries.pcss
src/components/Captcha/Captcha.pcss
src/components/ChangePassword/ChangePassword.pcss
src/components/EmailForm/EmailForm.pcss
src/components/SignIn/SignIn.pcss
src/components/SignUp/SignUp.pcss
src/containers/ChangePassword/ChangePassword.pcss
src/screens/ForgotPassword/ForgotPassword.pcss
src/screens/ProfileScreen/ProfileScreen.pcss
src/screens/SignInScreen/SignInScreen.pcss
src/screens/SignUpScreen/SignUpScreen.pcss
src/styles/themes/dark.pcss
src/styles/themes/light.pcss

https://monosnap.com/file/3lU6pYeVfmZCTFLvYXcK0Kgc81vcTB

Fix: unify email forms styles

---

src/components/Markets/__snapshots__/Markets.test.tsx.snap
src/custom/translations/ru.ts
src/translations/en.ts

https://jira.openware.work/browse/EMI-426

Fix: profile kyc naming

---

src/containers/RecentTrades/Market.tsx
src/containers/RecentTrades/RecentTradesTableCell.tsx
src/containers/RecentTrades/Yours.tsx

Fix: polish Recent Trades after wrong rebase

---

mocks/api/v2/peatio/public/currencies/GET.mock
src/components/CryptoIcon/__snapshots__/CryptoIcon.test.tsx.snap
src/components/CryptoIcon/index.tsx
src/components/CurrencyInfo/index.tsx
src/components/WalletItem/__snapshots__/WalletItem.test.tsx.snap
src/components/WalletItem/index.tsx

https://jira.openware.work/browse/EMI-423

Fix: wallets currency item consistency when the currency icon_url exists

---

src/screens/ProfileTwoFactorAuthScreen/ProfileTwoFactorAuthScreen.pcss
src/screens/ProfileTwoFactorAuthScreen/index.tsx
src/screens/tests/__snapshots__/ProfileTwoFactorAuthScreen.test.tsx.snap

https://jira.openware.work/browse/EMI-422

Fix: adjust 2fa layout for russian lang

---

src/components/PasswordStrengthMeter/PasswordStrengthMeter.pcss
src/components/SignUp/SignUp.pcss
src/containers/ReferralProgram/ReferralProgram.pcss
src/screens/EmailVerification/EmailVerification.pcss
src/screens/ProfileScreen/ProfileScreen.pcss
src/screens/SignInScreen/index.tsx

https://jira.openware.work/browse/EMI-430

Fix: Email verification styles (regression bug)

---

src/screens/ProfileTwoFactorAuthScreen/index.tsx
src/screens/tests/__snapshots__/ProfileTwoFactorAuthScreen.test.tsx.snap

https://jira.openware.work/browse/EMI-319

Fix: 2FA app store link

---

src/containers/ToolBar/MarketSelector/index.tsx

https://jira.openware.work/browse/EMI-453

Fix: search icon in market selector

---

mocks/api/v2/peatio/account/deposits/GET--page=1&limit=25.mock
src/containers/TwoFactorAuth/TwoFactorAuth.pcss
src/custom/translations/ru.ts
src/mobile/components/HistoryTable/index.tsx
src/translations/en.ts

* Fix: missing translation for processing deposit
* Fix: 2fa form height
* Fix: update snapshots to pass tests

Fix: deposit translations, 2fa form height (#453)

---

src/components/Customization/Themes/ColorSettings/ColorSettings.pcss
src/components/Customization/Themes/Themes.pcss
src/hooks/useSetMobileDevice.ts

Fix: update master with latest fixes

---

mocks/api/v2/peatio/account/beneficiaries/10/DELETE.mock
mocks/api/v2/peatio/account/beneficiaries/10/OPTIONS.mock
src/components/UploadFile/index.tsx

Apply commit fixes from TrakX:
8158d5257 Fix: update beneficiaries after delete
f314c1530 Fix: upload only allowed types of files

Fix: add list of acceptable documents types to upload

---

src/containers/Confirm/Address/index.tsx

Fix postcode regex

---

mocks/ranger.js
src/containers/OrderBook/index.tsx
src/modules/index.ts
src/modules/public/recentTrades/reducer.test.ts
src/modules/public/recentTrades/reducer.ts
src/modules/public/recentTrades/selectors.ts
src/modules/user/history/types.ts

This patch sovles issue with wrong last price in the order book and doesn't solve same issue for other components on the Trading UI. Need to fix tickers syncronization for the correct effect.

Feature: use last trade to display market price in order book

---

web/src/screens/SignUpScreen/index.tsx

https://openware-inc.atlassian.net/browse/OPSM-1810
Barong 2.6: https://github.com/openware/barong/blob/2-6-stable/app/api/v2/identity/users.rb#L62

Fix: send correct param refid on signup

---

web/src/custom/translations/ru.ts
web/src/translations/en.ts

[Jira Ticket](https://openware-inc.atlassian.net/browse/OPSM-1896)
Fix add fiat beneficiary address label from `Description` to `Beneficiary Name`

Fix: add fiat beneficiary address label

---

web/src/components/WalletsHeader/index.tsx
web/src/containers/Wallets/WalletsOverview/index.tsx
web/src/containers/Wallets/WalletsP2P/index.tsx
web/src/containers/Wallets/WalletsSpot/index.tsx
web/src/containers/Wallets/WalletsTransfer/index.tsx

[Jira Ticket](https://openware-inc.atlassian.net/browse/NAIR-200)
Fix search value in wallets transfer tab reset to default after web socket updated.

Fix: wallet search value reset after ws update

---

web/mocks/api/v2/barong/resource/api_keys/GET--page=1&limit=4.mock
web/src/components/TabPanel/TabPanel.pcss
web/src/components/Table/Table.pcss
web/src/containers/Order/Order.pcss
web/src/containers/OrderBook/OrderBook.pcss
web/src/containers/P2P/TradesHistory/P2PTradesHistory.pcss
web/src/containers/P2P/UserOffers/P2PUserOffers.pcss
web/src/containers/ProfileApiKeys/ProfileApiKeys.pcss
web/src/containers/RecentTrades/RecentTrades.pcss
web/src/containers/ReferralProgram/ReferralProgram.pcss
web/src/index.pcss
web/src/mobile/styles/components/Orders.pcss
web/src/screens/History/HistoryTab.pcss
web/src/screens/OrdersTabScreen/OrdersTabScreen.pcss
web/src/screens/P2P/P2POffersScreen/P2POffersScreen.pcss
web/src/screens/P2P/P2PUserOffersScreen/P2PUserOffersScreen.pcss
web/src/screens/ProfileScreen/ProfileScreen.pcss

system font 'IBM Plex Sans'
tab panel styles
table styles
fix custom control style

Fix: p2p styles

---

web/src/containers/P2P/CreateOffer/CreateOffer.pcss
web/src/containers/P2P/UserOffers/P2PUserOffers.pcss

make tab panel background transparent
my offer orders table height, color

Fix: p2p create offer tab panel background + my offer orders table style

---

web/src/containers/P2P/Offers/P2POffersHeader.tsx
web/src/screens/P2P/P2POffersScreen/index.tsx

[Jira Ticket](https://openware-inc.atlassian.net/browse/NAIR-189)
Fix missing "ALL" filter in payment method on p2p offer list.

Fix: missing filter all in p2p payment method

---

web/src/containers/Wallets/WalletsTransfer/index.tsx

[Jira Ticket](https://openware-inc.atlassian.net/browse/NAIR-190)
Hide p2p wallet from wallet transfer list if disabled from Tower.

Fix: hide disabled p2p wallet from transfer list

---

web/src/containers/P2P/Offers/P2POffersModal.tsx

[Jira Ticket](https://openware-inc.atlassian.net/browse/NAIR-196)
Fix calculation logic for 'ALL' button on buy P2P modal.

Fix: buy p2p modal logic for all amount button

---

web/src/containers/P2P/CreateOffer/Step2/index.tsx

[Jira Ticket](https://openware-inc.atlassian.net/browse/NAIR-197)
Fix payment method keep changed randomly after add or remove payment method on create offer screen step 2.

Fix: incorrect payment method icon on create new offer step 2

---

web/src/containers/P2P/OrderWaitPayment/index.tsx

[Jira Ticket](https://openware-inc.atlassian.net/browse/NAIR-211)
Fix incorrect confirm receive amount in checkbox of order confirmation modal.

Fix: incorrect receive amount in confirm order modal

---

web/src/containers/P2P/TradesHistory/index.tsx

[Jira Ticket](https://openware-inc.atlassian.net/browse/NAIR-210)
Fix incorrect user displayed in counterparty column in P2P history table.

Fix: p2p trade history counter party value

---

web/src/custom/translations/ru.ts
web/src/modules/user/p2pDispute/sagas/createP2PDisputesSaga.ts
web/src/translations/en.ts

[Jira Ticket](https://openware-inc.atlassian.net/browse/NAIR-216)
Add alert after submit dispute.

Fix: add alert after submit dispute

---

web/src/screens/P2P/P2POffersScreen/P2POffersScreen.pcss

[Jira Ticket](https://openware-inc.atlassian.net/browse/NAIR-229)
Fix template customization button overlap on P2P offer list.

Fix: template customize button overlap p2p list

---

web/src/containers/P2P/Offers/index.tsx

[Jira Ticket](https://openware-inc.atlassian.net/browse/NAIR-221)
Fix offer completion percentage to display maximum 2 precision.

Fix: offer completion rate precision

---

web/src/containers/P2P/Offers/index.tsx

[Jira Ticket](https://openware-inc.atlassian.net/browse/NAIR-223)
Show zero completion percentage for P2P offers in offer screen.

Fix: show zero completion percentage for offer

---

web/src/containers/P2P/Offers/P2POffersModal.tsx

[Jira Ticket](https://openware-inc.atlassian.net/browse/NAIR-252) 
Fix max order limit to not exceed offer available amount for placeholder and validation logic.

Fix: max order limit exceed offer available

---

web/src/containers/P2P/Offers/P2POffersModal.tsx

[Jira Ticket](https://openware-inc.atlassian.net/browse/NAIR-196)
Fix P2P sell order modal when click ALL button to select lower amount between offer available and current user balance.

Fix: p2p sell order all button amount calculation

---

web/src/screens/ProfileScreen/index.tsx

click API Key tab, click Security tab.
It should show Security box and Profile Verification box.

Fix: profile tab behaviour

---

web/src/components/Beneficiaries/BeneficiariesAddModal.tsx
web/src/containers/Wallets/EstimatedValue/index.tsx
web/src/containers/Wallets/WalletsOverview/index.tsx
web/src/containers/Wallets/WalletsP2P/index.tsx
web/src/containers/Wallets/WalletsSpot/index.tsx
web/src/containers/Wallets/WalletsTransfer/index.tsx
web/src/screens/WalletsScreen/index.tsx

https://openware-inc.atlassian.net/browse/OPSM-2208
Markets were loading on Trading page because in Redux markets state was rewritten after duplicating marketsFetch action.

Fix: continuous markets loading

---

web/src/custom/translations/ru.ts
web/src/translations/en.ts

https://openware-inc.atlassian.net/browse/OPSM-2306

Fix: add translation for invalid totp error

---

handlers/index.go
web/public/config.js

[Jira ticket](https://openware-inc.atlassian.net/jira/servicedesk/projects/OPSM/queues/custom/2/OPSM-2199)

Fix: redirect allowed user from /restriction, /maintenance page

---

web/src/containers/Wallets/EstimatedValue/EstimatedValue.pcss

https://openware-inc.atlassian.net/browse/OPSM-2321
master branch already has good style.
silwana branch is 3-0-stable, so I fixed from that branch.

Fix: estimated value style in wallet page

---

web/src/components/TwoFactorAuth/TwoFactorAuth.test.tsx
web/src/components/TwoFactorAuth/index.tsx
web/src/containers/ProfileApiKeys/index.tsx
web/src/custom/translations/ru.ts
web/src/screens/SignInScreen/index.tsx
web/src/translations/en.ts

https://openware-inc.atlassian.net/browse/OPSM-2307

Fix: use CodeVerification component for login 2fa form

---

web/mocks/api/v2/peatio/account/deposits/GET.mock
web/src/containers/Wallets/History.tsx
web/src/modules/user/history/types.ts

https://openware-inc.atlassian.net/browse/OPSM-2341

Fix: deposit history BitGo confirmations count "N/A"

---

web/src/modules/public/alert/sagas/handleAlertSaga.ts

https://openware-inc.atlassian.net/browse/OPSM-2333

Fix: show alert message when create beneficiaries error

---

web/src/custom/translations/ru.ts
web/src/translations/en.ts

[Jira Ticket](https://openware-inc.atlassian.net/browse/OPSM-2441)
Fix missing translation in wallets currency screen (mobile).

Fix: missing translation wallets balance

---

web/src/mobile/components/Header/index.tsx

[Jira Ticket](https://openware-inc.atlassian.net/browse/OPSM-2444)
Fix missing header section on home tab when using mobile resolution.

Fix: (mobile) missing header on home page

---

web/src/constants/index.ts

[Jira](https://openware-inc.atlassian.net/browse/OPSM-2654)

Fix: remove p2p from sidebar items for 3.0

---

web/src/custom/translations/ru.ts
web/src/mobile/components/HistoryTable/index.tsx
web/src/translations/en.ts

https://openware-inc.atlassian.net/browse/OPSM-2757

Fix: errored deposit state added to translations

---

web/mocks/api/v2/finex/market/orders/cancel/162421/OPTIONS.mock
web/mocks/api/v2/finex/market/orders/cancel/162421/POST--id=162421.mock
web/mocks/api/v2/finex/market/orders/cancel/162432/OPTIONS.mock
web/mocks/api/v2/finex/market/orders/cancel/162432/POST--id=162432.mock
web/mocks/api/v2/finex/market/orders/cancel/162543/OPTIONS.mock
web/mocks/api/v2/finex/market/orders/cancel/162543/POST--id=162543.mock
web/src/custom/translations/ru.ts
web/src/mobile/translations/en.ts
web/src/mobile/translations/ru.ts
web/src/translations/en.ts

To resolve ticket: https://openware-inc.atlassian.net/browse/OPSM-2655

Fix: order error translation

---

web/src/containers/Confirm/Address/index.tsx
web/src/containers/Confirm/Documents/index.tsx
web/src/containers/Confirm/Identity/index.tsx
web/src/containers/Confirm/Phone/Phone.pcss
web/src/containers/Confirm/Phone/index.tsx
web/src/modules/user/kyc/documents/actions.ts
web/src/modules/user/kyc/documents/reducer.ts
web/src/modules/user/kyc/documents/sagas/sendDocumentsSaga.test.ts
web/src/modules/user/kyc/documents/sagas/sendDocumentsSaga.ts
web/src/modules/user/kyc/identity/reducer.test.ts
web/src/modules/user/kyc/identity/reducer.ts
web/src/modules/user/kyc/identity/selectors.ts
web/src/modules/user/kyc/phone/reducer.test.ts
web/src/modules/user/kyc/phone/reducer.ts
web/src/modules/user/kyc/phone/selectors.ts
web/src/screens/ConfirmScreen/ConfirmScreen.pcss

https://openware-inc.atlassian.net/browse/OPSM-2742

Improvement: loading state of button after submit on KYC

---

web/src/containers/TradingChart/index.tsx

Add fallback method to set new symbol for trading view chart if widget not response from update method (timeout 3 seconds).
Issue occurred in CentraEx Prod.

Fix: add set new chart for tvWidget

---

web/src/containers/Wallets/WalletsSpot/index.tsx

[Jira Ticket](https://openware-inc.atlassian.net/browse/BIS-145)
Fix to only fetch beneficiaries when on wallet withdrawal tab.
See more detail in ticket description.

Fix: fetch beneficiary on withdraw tab

---

web/src/assets/images/CopyIcon.tsx
web/src/components/CopyableTextField/CopyableTextField.pcss
web/src/components/CustomInput/CustomInput.pcss
web/src/components/DepositCrypto/DepositCrypto.pcss
web/src/components/InputWithButton/index.tsx
web/src/containers/Wallets/WalletsSpot/WalletsSpot.pcss
web/src/translations/en.ts

[Jira Ticket](https://openware-inc.atlassian.net/browse/BIS-177)
Fix input style on wallet deposit tab.

Fix: input style on wallet deposit tab

---

web/src/components/ChangePassword/ChangePassword.pcss

[Jira Ticket](https://openware-inc.atlassian.net/browse/BIS-181)
Fix style on profile change password modal.

Fix: input style on profile change password modal

---

web/src/components/CustomInput/CustomInput.pcss
web/src/components/SignIn/SignIn.pcss
web/src/components/SignUp/SignUp.pcss
web/src/screens/SignUpScreen/SignUpScreen.pcss

https://openware-inc.atlassian.net/browse/BIS-172
https://openware-inc.atlassian.net/browse/BIS-173
https://www.figma.com/file/o32beobGrHFUk4M7xBjQva/BaseApp---Color-Theme-%2F-Base-Mockups?node-id=13209%3A202239

Fix: sign in, sign up style same as figma

---

web/src/components/InternalTransfer/InternalTransfer.pcss
web/src/components/InternalTransfer/index.tsx

https://openware-inc.atlassian.net/browse/BIS-180
https://www.figma.com/file/o32beobGrHFUk4M7xBjQva/BaseApp---Color-Theme-%2F-Base-Mockups?node-id=10968%3A117034

Fix: internal transfer style

---

web/mocks/ranger.js
web/src/modules/public/ranger/sagas/rangerSaga.ts
web/src/modules/user/ordersHistory/helpers.ts

https://openware-inc.atlassian.net/browse/OPD-561

Fix: push trigger_wait orders to state with WS

---

web/src/components/InputWithButton/index.tsx
web/src/containers/ProfileApiKeys/index.tsx
web/src/screens/ProfileScreen/ProfileScreen.pcss

[Jira Ticket](https://openware-inc.atlassian.net/browse/BIS-175)
Fix input style on profile api key created modal.

Fix: input style on api created modal

---

web/src/modules/user/wallets/selectors.ts

[Jira Ticket](https://openware-inc.atlassian.net/browse/BIS-233)
Fix logic to check for fetching wallet when has empty list.

Fix: check fetch wallet on empty list

---

web/src/components/UploadFile/UploadFile.pcss
web/src/components/UploadFile/index.tsx
web/src/containers/Confirm/Address/index.tsx
web/src/containers/Confirm/Documents/index.tsx
web/src/custom/translations/ru.ts
web/src/mobile/styles/screens/ConfirmMobileScreen.pcss
web/src/screens/ConfirmScreen/ConfirmScreen.pcss
web/src/translations/en.ts

[Jira Ticket](https://openware-inc.atlassian.net/browse/BIS-184)
Update input styles on profile KYC steps.

Fix: input style on kyc steps

---

web/mocks/api/v2/sonic/public/config/GET.mock
web/src/api/config.ts
web/src/api/types.ts
web/src/components/Beneficiaries/BeneficiariesCrypto/BeneficiariesBlockchainItem.tsx
web/src/components/Beneficiaries/BeneficiariesCrypto/SelectBeneficiariesCrypto.tsx
web/src/constants/index.ts
web/src/containers/Withdraw/UserWithdrawalLimits.tsx
web/src/containers/Withdraw/index.tsx

[Jira Ticket](https://openware-inc.atlassian.net/browse/OPD-762)
Fix to read platform currency config from sonic.

Fix: read platform currency config

---

web/mocks/api/v2/peatio/account/balances/GET.mock
web/mocks/api/v2/peatio/account/balances/luna/GET.mock
web/mocks/api/v2/peatio/account/balances/luna/OPTIONS.mock
web/mocks/api/v2/peatio/account/deposit_address/luna/GET.mock
web/mocks/api/v2/peatio/account/deposit_address/luna/OPTIONS.mock
web/mocks/api/v2/peatio/public/currencies/GET.mock
web/src/components/Beneficiaries/BeneficiariesAddModal.tsx

Related to ticket https://openware-inc.atlassian.net/browse/XLN-28

Feature : Add luna as memo based asset

---

web/src/assets/images/PasteIcon.tsx
web/src/components/Beneficiaries/Beneficiaries.pcss
web/src/components/Beneficiaries/BeneficiariesActivateModal.tsx
web/src/components/Beneficiaries/BeneficiariesAddModal.tsx
web/src/components/CodeVerification/CodeVerification.pcss
web/src/components/CodeVerification/index.tsx
web/src/components/CopyableTextField/index.tsx
web/src/components/CustomInput/CustomInput.pcss
web/src/components/InputWithButton/index.tsx
web/src/components/TwoFactorAuth/index.tsx
web/src/containers/ModalWithdrawConfirmation/ModalWithdrawConfirmation.pcss
web/src/containers/ModalWithdrawConfirmation/index.tsx
web/src/containers/TwoFactorAuth/TwoFactorAuth.pcss
web/src/containers/Wallets/WalletsSpot/WalletsSpot.pcss
web/src/custom/translations/ru.ts
web/src/mobile/components/WalletWithdrawBody/index.tsx
web/src/mobile/styles/components/WalletWithdrawBody.pcss
web/src/screens/SignInScreen/SignInScreen.pcss
web/src/translations/en.ts

[Jira Ticket 1](https://openware-inc.atlassian.net/browse/BIS-178)
[Jira Ticket 2](https://openware-inc.atlassian.net/browse/BIS-179)
Update input styles for wallet add whitelist and confirm add new whitelist popup.

Fix: input style on wallet add whitelist and confirm popup

---

go.mod
go.sum

https://openware-inc.atlassian.net/browse/OPSM-2262

Enhancement: update pkg/jwt version

---

web/mocks/api/v2/finex/public/markets/GET.mock
web/src/containers/Order/index.tsx
web/src/modules/public/markets/types.ts

https://openware-inc.atlassian.net/browse/OPD-723

Fix: advanced order type dropdown from backend

---

web/src/components/ChangePassword/ChangePassword.pcss
web/src/screens/ChangeForgottenPasswordScreen/ChangeForgottenPasswordScreen.pcss
web/src/screens/ForgotPassword/ForgotPassword.pcss

- forgot password
- reset password
- profile page change password modal
https://openware-inc.atlassian.net/browse/BIS-174
https://www.figma.com/file/o32beobGrHFUk4M7xBjQva/BaseApp---Color-Theme-%2F-Base-Mockups?node-id=13209%3A202239

Fix: forgot password, reset password style

---

web/src/components/Beneficiaries/Beneficiaries.pcss
web/src/components/Beneficiaries/index.tsx
web/src/components/DoubleDropdownSelector/DoubleDropdownSelector.pcss
web/src/components/Dropdown/Dropdown.pcss
web/src/components/InternalTransfer/InternalTransfer.pcss
web/src/components/Modal/Modal.pcss
web/src/components/TransferForm/TransferForm.pcss
web/src/components/WalletsHeader/WalletsHeader.pcss
web/src/containers/ModalWithdrawConfirmation/index.tsx
web/src/containers/ProfilePayment/PaymentMethodModal.tsx
web/src/containers/ProfilePayment/ProfilePayment.pcss
web/src/containers/QuickExchange/QuickExchange.pcss
web/src/containers/ReferralProgram/ReferralProgram.pcss
web/src/containers/Wallets/WalletsSpot/WalletsSpot.pcss
web/src/custom/translations/ru.ts
web/src/translations/en.ts

https://openware-inc.atlassian.net/browse/OPD-798

Fix: 3.1 input fields and label style

---

web/mocks/api/v2/p2p/public/payment_methods/GET.mock
web/src/containers/ProfilePayment/PaymentMethodModal.tsx

https://openware-inc.atlassian.net/browse/OPD-956

Fix: data format for the payment method dropdown

---

web/mocks/api/v2/finex/public/markets/GET.mock
web/mocks/ranger.js
web/src/components/Order/index.tsx
web/src/components/OrderForm/index.tsx
web/src/containers/Order/index.tsx

https://openware-inc.atlassian.net/browse/OPD-981

Fix: advanced order types

---

web/mocks/api/v2/sonic/public/config/GET.mock
web/src/containers/Wallets/WalletsOverview/index.tsx
web/src/helpers/estimateValue.ts

[Jira Ticket](https://openware-inc.atlassian.net/browse/OPD-974)
Use platform currency to calculate wallet estimated values.

Fix: use platform currency to calculate estimated wallet value

---

web/src/containers/Wallets/WalletsP2P/index.tsx

[Jira Ticket](https://openware-inc.atlassian.net/browse/OPD-977)
Add fetch p2p currencies list on wallet p2p tab.

Fix: fetch p2p currencies on p2p wallet screen

---

web/src/containers/ToolBar/MarketSelector/MarketSelector.pcss
web/src/containers/ToolBar/MarketSelector/MarketsList/MarketsList.pcss

https://openware-inc.atlassian.net/browse/OPD-1015

Fix: trading page market selector style

---

web/mocks/api/v2/peatio/account/withdraws/GET--page=1&limit=25.mock
web/src/containers/HistoryElement/index.tsx
web/src/custom/translations/ru.ts
web/src/helpers/historyTableUtils.ts
web/src/translations/en.ts

[Jira Ticket](https://openware-inc.atlassian.net/browse/OPD-1026)
Fix withdraw history under review status translation.
Fix translation for deposit txid header.

Fix: withdraw history under review translation

---

web/src/custom/translations/ru.ts
web/src/translations/en.ts

[Jira Ticket](https://openware-inc.atlassian.net/browse/OPD-1023)
Add translation for quick exchange history on wallet screen tabs.

Fix: add quick exchange history translation

---

web/src/containers/Markets/index.tsx

[Jira Ticket](https://openware-inc.atlassian.net/browse/OPD-1016)
Fix missing color for market price change percentage.

Fix: missing market price change percentage color

---

web/src/helpers/layout.ts

[Jira Ticket](https://openware-inc.atlassian.net/browse/OPD-1014)
Expand full height for trading grid layout.

Fix: expand full trading grit layout

---

web/src/components/Beneficiaries/DropdownBeneficiary.tsx

https://openware-inc.atlassian.net/browse/OPD-1052

Fix: do not allow to select disabled network in add beneficiary modal

---

web/src/components/InternalTransfer/InternalTransfer.pcss

[Jira Ticket](https://openware-inc.atlassian.net/browse/OPD-1056)
Fix internal transfer currency dropdown style.

Fix: internal transfer currency dropdown

---

web/mocks/api/v2/peatio/public/config/GET.mock
web/src/containers/Wallets/WalletsOverview/index.tsx
web/src/helpers/estimateValue.ts

[Jira Ticket](https://openware-inc.atlassian.net/browse/OPD-974)
Fix wallet total estimated value calculation.

Fix: wallet total estimated value calculation

---

web/mocks/api/v2/peatio/account/beneficiaries/GET--currency_id=btc&state[]=active&state[]=pending.mock
web/src/containers/ModalWithdrawConfirmation/index.tsx
web/src/containers/Wallets/WalletsSpot/index.tsx
web/src/modules/user/beneficiaries/types.ts

[Jira Ticket](https://openware-inc.atlassian.net/browse/OPD-1054)
Show blockchain network on withdraw confirmation window

Fix: show blockchain network on withdraw confirmation window

---

web/src/components/Beneficiaries/BeneficiariesAddModal.tsx
web/src/components/Beneficiaries/DropdownBeneficiary.tsx

https://openware-inc.atlassian.net/browse/OPD-1052

Fix: prevent selecting disabled network

---

web/src/components/InternalTransfer/InternalTransfer.pcss

[Jira Ticket](https://openware-inc.atlassian.net/browse/OPD-1079)
Fix 2fa overlay position on internal transfer screen.

Fix: internal transfer 2fa overlay

---

web/src/components/CopyableTextField/index.tsx
web/src/components/InputWithButton/index.tsx
web/src/containers/Wallets/WalletsSpot/WalletsSpot.pcss
web/src/containers/Withdraw/index.tsx

https://openware-inc.atlassian.net/browse/OPD-1053

Fix: withdraw amount input style

---

web/mocks/api/v2/peatio/account/withdraws/OPTIONS.mock
web/mocks/api/v2/peatio/account/withdraws/POST.mock
web/src/containers/Withdraw/index.tsx

https://openware-inc.atlassian.net/browse/OPD-1067
Keep state beneficiary value after successful withdraw

Fix: withdraw success reset component state

---

web/src/api/config.ts
web/src/api/types.ts
web/src/containers/TradingChart/api.ts
web/src/helpers/getStartTimestampPeriod.ts
web/src/helpers/index.ts

https://openware-inc.atlassian.net/browse/OPSM-3288

fix: default candle stick amount

---

web/src/helpers/getStartTimestampPeriod.ts

https://openware-inc.atlassian.net/browse/OPSM-3288
Fix convert start timestamp for candle stick in chart library.

fix: start timestamp candle stick period
